name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/NOME_DA_IMAGEM:latest
          docker build -t $IMAGE .
          docker push $IMAGE
